### ISSUE TITLE
Request payload size exceeds the limit: 10485760 bytes.

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [GoogleCloudPlatform/dotnet-docs-samples#845] opened 2019-06-21 16:12 UTC
I am getting an error running Recognize that says in in Visual Studio 2019 IDE in the Editor Window that says the following:

> "Request payload size exceeds the limit: 10485760 bytes."

Here are the details:

> Grpc.Core.RpcException
>   HResult=0x80131500
>   Message=Status(StatusCode=InvalidArgument, Detail="Request payload size exceeds the limit: 10485760 bytes.")
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
>    at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
>    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
>    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
>    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
>    at Google.Cloud.Speech.V1.Speech.SpeechClient.LongRunningRecognize(LongRunningRecognizeRequest request, CallOptions options)
>    at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
>    at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
>    at Google.Cloud.Speech.V1.SpeechClientImpl.LongRunningRecognize(LongRunningRecognizeRequest request, CallSettings callSettings)
>    at GoogleCloudSamples.Recognize.LongRunningRecognize(String filePath) in C:\Users\dbrow_000\dotnet-docs-samples-master\speech\api\Recognize\Recognize.cs:line 373
>    at GoogleCloudSamples.Recognize.<>c.<Main>b__17_1(AsyncOptions opts) in C:\Users\dbrow_000\dotnet-docs-samples-master\speech\api\Recognize\Recognize.cs:line 597
>    at GoogleCloudSamples.Recognize.Main(String[] args) in C:\Users\dbrow_000\dotnet-docs-samples-master\speech\api\Recognize\Recognize.cs:line 584
> 

I've had this error before. The file I'm using is less than an hour long. I thought there is a 480 minute max.

**Comment by jskeet** [comment] 2019-06-22 06:25
I'll look into this on Monday.

**Comment by jskeet** [comment] 2019-06-24 07:49
From https://cloud.google.com/speech-to-text/quotas:

> Audio longer than ~1 minute must use the uri field to reference an audio file in Google Cloud Storage.

So if you upload the file to Google Cloud Storage first (and change the code to recognize from there) I'd expect it to be fine.

Closing as I believe this is working as intended.

**Closed by jskeet** 2019-06-24 07:49 UTC
