### ISSUE TITLE
Request for sample for 'writing structured logs'

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/dotnet-docs-samples#2020] opened 2023-01-24 18:18 UTC
The following documentation page is missing a code snippet for "Writing structured logs" for C#:
https://cloud.google.com/functions/docs/monitoring/logging#writing_structured_logs

This request is based on sample feedback b/266181393

**Comment by amanda-tarafa** [comment] 2023-01-30 10:59
Closing as a duplicate of #1768

**Closed by amanda-tarafa** 2023-01-30 10:59 UTC
Labels: type: feature request, priority: p2, api: logging, samples
