### ISSUE TITLE
UpdateIntent overrites old training phrase instead of updating

### ISSUE THREAD

**Issue by chuksgpfr** [GoogleCloudPlatform/dotnet-docs-samples#997] opened 2020-03-30 16:25 UTC
The updateintent overrites old intents, see my code below.

`                      
                        trainingPhrase.Parts.AddRange(phraseParts);
                        intent.TrainingPhrases.Add(trainingPhrase);
                        var req = new UpdateIntentRequest();
                        req.Intent = intent;
                        client.UpdateIntent(req);
`

@amanda-tarafa

**Comment by amanda-tarafa** [comment] 2020-03-30 17:43
What exactly do you mean by "overwrite" and what do you expect "update" to do instead? Have you looked at the API documentation I linked in the previous issue and confirmed that this is not the expected behavior? 
In general my advice would be that you first determine what you want to achieve, then read the API documentation and the client library reference docs to find out how to achieve it, and only then write your code. If the code doesn't behave as expected according to the documentation then we'll be very happy to help and fix whatever might be wrong.

**Comment by amanda-tarafa** [comment] 2020-04-02 00:22
I'll be closing this issue now since we haven't had more info. Please do leave a comment if there was a problem with the client library or the samples.

**Closed by amanda-tarafa** 2020-04-02 00:22 UTC
Labels: api: dialogflow, type: question
