### ISSUE TITLE
Backup Exceptions

### ISSUE THREAD

**Issue by tellmeaboutcode** [GoogleCloudPlatform/dotnet-docs-samples#1583] opened 2022-01-09 01:44 UTC
I am seeing the below exception while creating the backups.

`Status(StatusCode="InvalidArgument", Detail="Invalid ListBackupOperations request.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1641686430.749211566","description":"Error received from peer ipv4:142.250.188.42:443","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Invalid ListBackupOperations request.","grpc_status":3}")`

```
var filter =
                $"(metadata.database={dbName}) AND " +
                "(metadata.@type:type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata) AND " +
                "done=false";

```

**Comment by amanda-tarafa** [comment] 2022-01-10 09:38
I've seen an uptick of these errors recently on our CI as well. I'm planning to look into this today.

**Comment by tellmeaboutcode** [comment] 2022-01-11 14:49
@amanda-tarafa Hi any update on this?

**Comment by amanda-tarafa** [comment] 2022-01-11 15:06
No, I'm sorry, not yet, I'll update here as soon as I know more.

**Comment by amanda-tarafa** [comment] 2022-01-11 17:54
OK, I can reproduce this also on my local environment and there's nothing inmmediately wrong with the sample code on this repo or with the client library itself.

The problem seems to be that the API has stopped accepting `metadata.database` as part of the filter. As a very temporary workaround, consider filtering for the Database locally?

In the meantime I'll reach out to the API team. @skuruppu FYI, I'm adding you as assignee as well in case you can take a look on the API side of things.

**Comment by tellmeaboutcode** [comment] 2022-01-13 14:40
@amanda-tarafa Thanks for working on this. Could you please explain/provide a sample code as to how to go about the temporary solution mentioned above?

**Comment by amanda-tarafa** [comment] 2022-01-13 14:51
@tellmeaboutcode we know more of what is happening, and the issue seems to be with the API requiring filter predicates to be in a particular order, so, if you modify your filter to what follows, it should work.

We are still looking at whether this API change should/can be reverted, etc. But for the time being, just rewrite your filter as a workaround.

```
$"(metadata.@type:type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata) AND " +
"(metadata.database={dbName}) AND " +
"(done=false)";
```

**Comment by amanda-tarafa** [comment] 2022-01-13 15:11
@tellmeaboutcode I've just got confirmation from the API team that a backwards compatible fix is on the way, but it might take 3 to 4 weeks to land. In the meantime, changing the order of the predicates on the filter may be use as a workaround.

I'm leaving this issue open until I've confirmed the fix is live. Thanks for reporting.

**Comment by tellmeaboutcode** [comment] 2022-01-13 15:43
@amanda-tarafa Thank you. Changing the order worked.

**Comment by amanda-tarafa** [comment] 2022-03-25 09:08
Closing as this has been addressed.

**Closed by amanda-tarafa** 2022-03-25 09:08 UTC
Labels: type: process, priority: p1, external, api: spanner, samples
