### ISSUE TITLE
storage: ListObjects is empty

### ISSUE THREAD

**Issue by andrescrd** [GoogleCloudPlatform/dotnet-docs-samples#1142] opened 2020-07-22 15:17 UTC
I am trying to get the list of objects in my bucket, sometimes it is satisfactory, but sometimes the list is empty.
I am using the example code.

var storage = StorageClient.Create();
foreach (var storageObject in storage.ListObjects(bucketName, prefix))
{ 
   Console.WriteLine(storageObject.Name);
}

Any Idea on this?

**Comment by jskeet** [comment] 2020-07-22 15:23
(For future issues about Google.Cloud.Storage.V1 that aren't specifically about samples, but just about how the API works, please file issues in https://github.com/googleapis/google-cloud-dotnet)

That will happen if no objects in the bucket match the specified prefix. If you have concrete examples of the actual object names and the prefix you're passing, please give us that information so that we can try to reproduce the problem - along with telling us whether this *always* happens for a given bucket/prefix, or whether it's intermittent. (You say "sometimes it is satisfactory" but it's not clear whether that's with the same bucket/prefix that fails.)

**Comment by amanda-tarafa** [comment] 2020-08-18 10:37
@andrescrd I'll be closing this issue now, since we can't help more without more info. Do please add a comment with the details we requested if you continue to have trouble.

**Closed by amanda-tarafa** 2020-08-18 10:37 UTC
Labels: needs more info, type: question
