### ISSUE TITLE
BigQueryTest.TestListTables fails sometimes with a Json parsing error

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1338] opened 2021-07-15 16:33 UTC
It might be the server returning some invalid Json in some instances. 

Failure can be seen [here](https://source.cloud.google.com/results/invocations/41ad3d5f-766f-45bf-af91-e8d2c0e5855b/log).

**Comment by Rishabh-V** [comment] 2022-02-18 11:50
Hi @amanda-tarafa,

As discussed and agreed in our call today, this failure appears to be due to transient HTTP 502 error response from the API on that day. The returned error was in HTML format which resulted in Json Parsing exception. This is currently not reproducible after trying the test case in 100 and 1000 iterations.  As suggested by you, closing this issue.

**Closed by Rishabh-V** 2022-02-18 11:50 UTC
Labels: type: process, priority: p2, api: bigquery, samples
