### ISSUE TITLE
InvalidOperationException: The Application Default Credentials are not available.

### ISSUE THREAD

**Issue by chuksgpfr** [GoogleCloudPlatform/dotnet-docs-samples#993] opened 2020-03-28 23:30 UTC
How do i fix this. I want to set my authentication in my code and not on the machine.
I have checked almost every answer on stackoverflow and github, but none has a good explanation.

How do i pass the credentials to the create intent, it throws this error.

> InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information

`//auth
GoogleCredential credential = GoogleCredential.FromFile(file);
            
            //var credential = GoogleCredential.FromStream(
            //  Assembly.GetExecutingAssembly().GetManifestResourceStream("chatbot.json"))
            //  .CreateScoped(IntentsClient.DefaultScopes);

            var storage = StorageClient.Create(credential);

            var client = IntentsClient.Create();

            var text = new Intent.Types.Message.Types.Text();
            text.Text_.Add("Message Text");

            var message = new Intent.Types.Message()
            {
                Text = text
            };
            var trainingPhrasesParts = new List<string>
            {
                "Book a fligt",
                "check cheap flights"
            };
            var phraseParts = new List<Intent.Types.TrainingPhrase.Types.Part>();
            foreach (var part in trainingPhrasesParts)
            {
                phraseParts.Add(new Intent.Types.TrainingPhrase.Types.Part()
                {
                    Text = part
                });
            }

            var trainingPhrase = new Intent.Types.TrainingPhrase();
            trainingPhrase.Parts.AddRange(phraseParts);

            var intent = new Intent();
            intent.DisplayName = "test";
            intent.Messages.Add(message);
            intent.TrainingPhrases.Add(trainingPhrase);

            var newIntent = client.CreateIntent(
                parent: new AgentName("chatbot"),
                intent: intent
            );`

**Comment by chuksgpfr** [comment] 2020-03-29 10:11
@amanda-tarafa any help?

**Comment by amanda-tarafa** [comment] 2020-03-29 10:37
Without looking at the stack trace, I'm guessing that you get the error on `var client = IntentsClient.Create();`.
The `<API>Client.Create()` method for API clients defined in Google.Cloud.* client libraries only creates the default client using default settings and default credentials. If you want to specify the credentianls yourself or other than the default settings then you need to use the `<API>ClientBuilder ` class. For creating an `IntentsClient` the code would look something like this:

```
IntentsClientBuilder builder = new IntentsClientBuilder
{
    CredentialsPath = "chatbot.json", // Relative to where the code is executing or absolute path.
    // Scopes = IntentsClient.DefaultScopes // Commented out because there's no need to specify this since you are using the defaults and all default values will be automatically used for values not specified in the builder.
};
IntentsClient client = builder.Build();
```
Also, take a look at [IntentsClientBuilder](https://googleapis.dev/dotnet/Google.Cloud.Dialogflow.V2/2.0.0/api/Google.Cloud.Dialogflow.V2.IntentsClientBuilder.html) reference.

**Comment by chuksgpfr** [comment] 2020-03-29 10:49
Works. Thanks @amanda-tarafa 

But there's another issue of my training phrase entering just one place.

Like on my dialogflow console, the training phrase i added through code, shows in one box

**Comment by amanda-tarafa** [comment] 2020-03-29 10:53
I'll be closing this issue now since it has been fixed.
For a different proble please a create a new issue. And please provide a good explanation of what you are doing, what result you are expecting and what result you are actually seeing. A very small program exactly reproducing the problem would be best, else please provide as much information as possible including error messages, stack traces, etc. (From your last comment and without any more informatio or context I wouldn't be able to help.)

**Closed by amanda-tarafa** 2020-03-29 10:53 UTC
Labels: type: question
