### ISSUE TITLE
Error on app engine deploy

### ISSUE THREAD

**Issue by pranav700** [GoogleCloudPlatform/dotnet-docs-samples#1239] opened 2021-01-12 19:15 UTC
Hello , I was trying with "Hello World" app for .net core and is failing at last step when trying to deploy to app engine flex with below error.

Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.

I cant find anything in logging too. please can you let me know what wrong I am doing here as I just cloned the repo and built it.

**Comment by amanda-tarafa** [comment] 2021-01-12 20:05
I'll take a look tomorrow and let you know.

**Comment by amanda-tarafa** [comment] 2021-01-12 20:07
Just for extra information, can you add the link with the instructions you are following to deploy? Or a description of exactly how you are trying to deploy. Thanks

**Comment by pranav700** [comment] 2021-01-12 20:26
sure, 
1. so I cloned the "Hello World" repo from github
2.  Open it in Visual studio and change the "Copy to Output Directory" Property to Copy if Newer.
3. Build the solution in release mode
4. Open google sdk cmd and change directory to HelloWorld\bin\Release\netcoreapp2.1
5. lastly, gcloud app deploy

Also I tried "Publish to Google Cloud" plugin in VS and it failed too with same error

```
Updating service [default] (this may take several minutes)...
..................................failed.
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
Failed to deploy project HelloWorld to App Engine Flex.
```

**Comment by amanda-tarafa** [comment] 2021-01-12 22:07
Thanks for the info. I'll try to reproduce tomorrow and report back here with my findings.

**Comment by amanda-tarafa** [comment] 2021-01-13 16:05
I just successfully deployed the [HelloWorld for App Engine](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/appengine/flexible/HelloWorld) app and was able to access it with my browser.

Can I double check that you have followed the instructions on the [README](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/appengine/flexible/HelloWorld/README.md) file for the project? Specially the instructions on the first step of the prerequisites and in particular all the steps around [the creation of a service account key](https://cloud.google.com/dotnet/docs/setup#create_a_service_account_key_for_authentication).
Notice that if you created the env var with the Google Cloud SDK shell already opened, that process won't pick up the env var. You need to open a new Google Cloud SDK shell after you have created the env var.

**Comment by amanda-tarafa** [comment] 2021-01-13 16:19
Can I ask also, in which region you are running? We've seen similar problems a couple of times (https://github.com/googleapis/google-cloud-dotnet/issues/4903) in regions that are running low on resources. In that case, changing to a different region might be a temporary workaround.

**Comment by pranav700** [comment] 2021-01-13 16:25
Thanks for the response. I'll definitely try again this evening. The region I was pointing to is europe-west2.

**Comment by pranav700** [comment] 2021-01-13 16:31
I just read the other thread, and will try with different region too

**Comment by pranav700** [comment] 2021-01-13 16:32
I just read the other thread, and will try with different region too

**Comment by pranav700** [comment] 2021-01-13 17:11
So I just tried it again, I was able to deploy successfully for us-central1 but europe-west2 is still failing.  Hope the issue gets fixed soon. Thanks for your help

**Comment by amanda-tarafa** [comment] 2021-01-13 17:17
Thanks for getting back to us. I'll be closing this issue now because there's no problem with the sample itself which is what we can help with.

**Closed by amanda-tarafa** 2021-01-13 17:17 UTC
Labels: priority: p2, samples, type: question
