### ISSUE TITLE
Can't select Firestore as native mode.

### ISSUE THREAD

**Issue by sourav-paul** [GoogleCloudPlatform/dotnet-docs-samples#983] opened 2020-03-20 07:47 UTC
All my other projects are selected to Firestore in native mode. But in one project I can't select it anywhere. Even inside the Datastore dashboard. It says no project exists.
![datastore dashboard](https://user-images.githubusercontent.com/6245802/77144751-e52de500-6ab0-11ea-87a2-606becac0ae4.PNG)

Firestore says to go to the Datastore dashboard.
![firestore dashboard](https://user-images.githubusercontent.com/6245802/77144767-f0811080-6ab0-11ea-9693-2126dc4765b6.PNG)

How do I select Firestore in native mode?

**Comment by jskeet** [comment] 2020-03-20 08:14
I suspect you have at some point created a Datastore database in that project, or have at least selected the Firestore in Datastore mode for that project at some point. What happens if you click on the "Go to Datastore page"?

As per https://cloud.google.com/datastore/docs/firestore-or-datastore:

> Warning: Once you select Firestore in Datastore mode and execute the first write on the database, you cannot switch to Firestore in Native mode.

Note that the maintainers of this repository aren't experts in individual APIs - we know more about the .NET client libraries, and they're not really relevant for this question. I would suggest visiting https://firebase.google.com/support for more Firebase/Firestore-specific support such as project configuration. I'm going to close this issue here as I'm afraid I don't think we'll be able to help you further.

**Closed by jskeet** 2020-03-20 08:14 UTC

**Comment by sourav-paul** [comment] 2020-03-20 08:51
Thanks @jskeet . 
When I click **Go to Datastore Page** it goes here.
![when clicked to go to datastore page](https://user-images.githubusercontent.com/6245802/77148385-b0725b80-6ab9-11ea-8bbf-2eb2989d195c.PNG)

In case this comment/attachment doesn't help, I'll contact firebase support.

**Comment by jskeet** [comment] 2020-03-20 08:52
Right - that's basically showing that that project has a Datastore database, so you can't use it in Firestore Native Mode, I'm afraid.

**Comment by sourav-paul** [comment] 2020-03-20 09:01
I just found the issue. Project default app engine was disabled. Cloud Firestore and Datastore use the default app engine under the hood. After enabling it, I could switch to native mode.

**Comment by jskeet** [comment] 2020-03-20 09:01
Excellent - glad to hear it!

**Comment by jimmyz500** [comment] 2020-07-20 01:45
@sourav-paul how did you enable the project default app engine? I am having the same issue, thanks.

**Comment by sourav-paul** [comment] 2020-07-20 01:56
> @sourav-paul how did you enable the project default app engine? I am having the same issue, thanks.

From the left side menu reach the compute section, where VMs, App Engine, Cloud Run etc is located and select app engine. You will be redirected to the app engine page from there.

**Comment by jimmyz500** [comment] 2020-07-20 02:10
Thanks for the quick response, when I go to the App Engine section, it just says Welcome to App Engine with a Get Started link.  So I am thinking it is enabled? For you it was actually disabled?

**Comment by sourav-paul** [comment] 2020-07-20 02:12
> Thanks for the quick response, when I go to the App Engine section, it just says Welcome to App Engine with a Get Started link. So I am thinking it is enabled? For you it was actually disabled?

Have you selected a Firestore as native database yet?

**Comment by jimmyz500** [comment] 2020-07-20 02:24
No, I get "This project uses another database service" and takes me to Datastore, I then get "Since your database is empty, you can still switch to Cloud Firestore in Native mode to get more features."
and finally:
"Unable to switch to Native mode
Your database mode couldn't be switched because you already added and deleted data at some point. You can always create a new project to use Cloud Firestore in Native mode."

I thought this is similar to your issue.

**Comment by sourav-paul** [comment] 2020-07-20 02:31
> No, I get "This project uses another database service" and takes me to Datastore, I then get "Since your database is empty, you can still switch to Cloud Firestore in Native mode to get more features."
> and finally:
> "Unable to switch to Native mode
> Your database mode couldn't be switched because you already added and deleted data at some point. You can always create a new project to use Cloud Firestore in Native mode."
> 
> I thought this is similar to your issue.

Have you edited data in Datastore in this project?

If yes, then you can't switch to Firestore anymore as you can only use one of Firestore and Datastore in a a project.

My case was, I selected native Firestore. Then disabled an app engine related to Firestore which is needed to run Firestore. Then I had to enable it back.

**Comment by jimmyz500** [comment] 2020-07-20 02:34
ok, got you, thanks for the help!

**Comment by Slavrix** [comment] 2022-02-01 04:06
@jimmyz500 did you find a solution to your issue? i think im getting the same problem as your case

**Comment by amanda-tarafa** [comment] 2022-02-01 09:33
@Slavrix if you read a few comments up you'll see that several people have commented on this thread, all with the same symptons but with different root causes. Try to go through those and see if any proposed solution solves your issue. If not, I would advise you to use some of the [support resources](https://cloud.google.com/firestore/docs/getting-support) for Firestore as they'll be able to help you better than we can. We focus here on .NET Client Libraries for Google Cloud and samples, but we are not necessarily savvy on each of the products themselves.

**Comment by LakshayDCoder** [comment] 2022-03-01 05:30
> > @sourav-paul how did you enable the project default app engine? I am having the same issue, thanks.
> 
> From the left side menu reach the compute section, where VMs, App Engine, Cloud Run etc is located and select app engine. You will be redirected to the app engine page from there. If you see it's disabled, enable it there.

@sourav-paul [sourav-paul](https://github.com/sourav-paul) I wanted to confirm. I haven't added any data to my datastore. When I go to App Engine I get a screen showing "Your App Engine application has been created". When I go to my datastore and click on switch back to native firestore, it gives me an error. Am I missing something? How did you switch back to native mode?

**Comment by Reriuqni** [comment] 2022-03-12 15:29
Hi,
What I did:
`https://console.cloud.google.com/datastore/entities/query/kind?project=<your  Project ID>`

![image](https://user-images.githubusercontent.com/7934626/158024150-e02f1c1d-4f3d-4c6f-a8f8-a248b3621f7b.png)

![image](https://user-images.githubusercontent.com/7934626/158024173-59db7399-ef2a-48cf-86d0-f9d0feaae66b.png)

![image](https://user-images.githubusercontent.com/7934626/158024178-aa8dfe00-cfcc-46b2-91ac-449bfd052ac3.png)

![image](https://user-images.githubusercontent.com/7934626/158024205-f74f4d6d-ca38-4c7f-a6a0-3397dd3dd472.png)

![image](https://user-images.githubusercontent.com/7934626/158024269-4e30051e-2fbf-421a-9257-9b3754c19357.png)

**Comment by LakshayDCoder** [comment] 2022-03-14 09:08
> Hi, What I did: `https://console.cloud.google.com/datastore/entities/query/kind?project=<your Project ID>`
> 
> [https://console.cloud.google.com/datastore/entities/query/kind](url)
> 
> ![image](https://user-images.githubusercontent.com/7934626/158024150-e02f1c1d-4f3d-4c6f-a8f8-a248b3621f7b.png)
> 
> ![image](https://user-images.githubusercontent.com/7934626/158024173-59db7399-ef2a-48cf-86d0-f9d0feaae66b.png)
> 
> ![image](https://user-images.githubusercontent.com/7934626/158024178-aa8dfe00-cfcc-46b2-91ac-449bfd052ac3.png)
> 
> ![image](https://user-images.githubusercontent.com/7934626/158024205-f74f4d6d-ca38-4c7f-a6a0-3397dd3dd472.png)
> 
> ![image](https://user-images.githubusercontent.com/7934626/158024269-4e30051e-2fbf-421a-9257-9b3754c19357.png)
> 
> .
> 
> maybe you have to enable service
> 
> ![image](https://user-images.githubusercontent.com/7934626/158025849-bce300a2-aa56-416c-8d0c-d3fe1b80d622.png)

I did the exact same thing but it's just not working. It is giving me this error.

![Screenshot 2022-03-14 at 2 33 39 PM](https://user-images.githubusercontent.com/32734770/158139888-582a73d3-108f-418f-a01b-3d98b1e28741.png)

Also, where do you enable the services that you mentioned ??

**Comment by Reriuqni** [comment] 2022-03-15 01:21
> > Hi, What I did: `https://console.cloud.google.com/datastore/entities/query/kind?project=<your Project ID>`
> > [https://console.cloud.google.com/datastore/entities/query/kind](url)
> > ![image](https://user-images.githubusercontent.com/7934626/158024150-e02f1c1d-4f3d-4c6f-a8f8-a248b3621f7b.png)
> > ![image](https://user-images.githubusercontent.com/7934626/158024173-59db7399-ef2a-48cf-86d0-f9d0feaae66b.png)
> > ![image](https://user-images.githubusercontent.com/7934626/158024178-aa8dfe00-cfcc-46b2-91ac-449bfd052ac3.png)
> > ![image](https://user-images.githubusercontent.com/7934626/158024205-f74f4d6d-ca38-4c7f-a6a0-3397dd3dd472.png)
> > ![image](https://user-images.githubusercontent.com/7934626/158024269-4e30051e-2fbf-421a-9257-9b3754c19357.png)
> > .
> > maybe you have to enable service
> > ![image](https://user-images.githubusercontent.com/7934626/158025849-bce300a2-aa56-416c-8d0c-d3fe1b80d622.png)
> 
> I did the exact same thing but it's just not working. It is giving me this error.
> 
> ![Screenshot 2022-03-14 at 2 33 39 PM](https://user-images.githubusercontent.com/32734770/158139888-582a73d3-108f-418f-a01b-3d98b1e28741.png)
> 
> Also, where do you enable the services that you mentioned ??

Hi @LakshayDCoder,
Try this

![image](https://user-images.githubusercontent.com/7934626/158286799-d40bbaee-47e2-4603-bf0f-4c1be2351b14.png)

![image](https://user-images.githubusercontent.com/7934626/158287183-3327bf1a-f0c0-471a-b38f-1c25cc22a0eb.png)

![image](https://user-images.githubusercontent.com/7934626/158287321-3e4e0908-c228-427e-ba68-4bd326852d35.png)



.
If you have enabled API, then it should be like:

![image](https://user-images.githubusercontent.com/7934626/158285874-a6540766-4355-4587-b868-6a89f8b6d113.png)

![image](https://user-images.githubusercontent.com/7934626/158286047-3ce4c4b4-f916-4e62-9f48-58623d7eb776.png)

![image](https://user-images.githubusercontent.com/7934626/158286726-6acc0f2c-785b-4a6c-aeb3-1e6ae5c27eb5.png)
